"""Generate the two MBD-Framework notebooks on disk."""
import json, os

NB_DIR = r"C:\MBD-Framework\notebooks"
os.makedirs(NB_DIR, exist_ok=True)

META = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.11.0"},
}

# ═══════════════════════════════════════════════════════════════════════
# NOTEBOOK 01 — Paper 1: Baseline Deviation
# ═══════════════════════════════════════════════════════════════════════

nb01 = {"cells": [], "metadata": META, "nbformat": 4, "nbformat_minor": 4}

def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}

def code(src):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

nb01["cells"] = [
    md([
        "# Paper 1: Memory as Baseline Deviation\n",
        "\n",
        "**DOI:** [10.5281/zenodo.17381536](https://doi.org/10.5281/zenodo.17381536)\n",
        "\n",
        "This notebook walks through the core equation of the MBD framework:\n",
        "\n",
        "$$B(t+1) = B(t)(1 - \\lambda) + I(t) \\cdot \\lambda$$\n",
        "\n",
        "where:\n",
        "- $B(t)$ is the **baseline** (the agent's resting personality state) at time $t$\n",
        "- $I(t)$ is the **input signal** (trauma, joy, novelty) at time $t$\n",
        "- $\\lambda \\in [0, 1]$ is the **plasticity parameter** (how deeply the event rewrites the baseline)\n",
        "\n",
        "Every plot below is generated from the actual framework source code.",
    ]),
    code([
        "import sys, os\n",
        "sys.path.insert(0, os.path.abspath('..'))\n",
        "\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from analysis.trauma_model import (\n",
        "    Baseline, TraumaForm, update_baseline, update_kappa, Interaction\n",
        ")\n",
        "\n",
        "print('Framework loaded.')",
    ]),
    md([
        "## 1. The Baseline Vector\n",
        "\n",
        "An agent's personality is not a label \u2014 it is a **vector** in state space.\n",
        "We use three dimensions from the VAD (Valence\u2013Activation\u2013Dominance) model:\n",
        "\n",
        "| Dimension | Range | Meaning |\n",
        "|-----------|-------|---------|\n",
        "| **Valence** | -1 to +1 | Negative \u2190 \u2192 Positive affect |\n",
        "| **Activation** | -1 to +1 | Calm \u2190 \u2192 Energised |\n",
        "| **Dominance** | -1 to +1 | Submissive \u2190 \u2192 Dominant |\n",
        "\n",
        "The baseline is where you *return to* after perturbation \u2014 your emotional\n",
        "centre of gravity.",
    ]),
    code([
        "B0 = Baseline([0.5, -0.2, 0.1])\n",
        "print(f'Initial baseline B0 = {B0.vector}')\n",
        "print(f'  Valence:    {B0.vector[0]:+.2f}  (mildly positive)')\n",
        "print(f'  Activation: {B0.vector[1]:+.2f}  (slightly calm)')\n",
        "print(f'  Dominance:  {B0.vector[2]:+.2f}  (near neutral)')",
    ]),
    md([
        "## 2. Trauma as a Mathematical Object\n",
        "\n",
        "A `TraumaForm` packages three things:\n",
        "- **input_signal**: A vector that pushes the baseline in some direction\n",
        "- **lambda_learning_rate** ($\\lambda$): How deeply this event rewrites the baseline\n",
        "- **description**: Human-readable label\n",
        "\n",
        "High $\\lambda$ = the event *changes who you are*. Low $\\lambda$ = a ripple that fades.",
    ]),
    code([
        "events = [\n",
        "    TraumaForm(np.array([-0.8,  0.5, -0.6]), 0.3, 'Sudden loss'),\n",
        "    TraumaForm(np.array([-0.3,  0.2, -0.2]), 0.1, 'Chronic stress'),\n",
        "    TraumaForm(np.array([ 0.4, -0.1,  0.3]), 0.2, 'New friendship'),\n",
        "    TraumaForm(np.array([-0.9,  0.7, -0.8]), 0.5, 'Betrayal'),\n",
        "    TraumaForm(np.array([ 0.6,  0.3,  0.4]), 0.15,'Milestone achievement'),\n",
        "    TraumaForm(np.array([ 0.7, -0.2,  0.5]), 0.4, 'Deep recovery'),\n",
        "]\n",
        "\n",
        "hdr = ('Event', 'Signal', 'lambda')\n",
        "print(f'{hdr[0]:<25} {hdr[1]:>25} {hdr[2]:>7}')\n",
        "print('-' * 60)\n",
        "for e in events:\n",
        "    sig_str = np.array2string(e.input_signal, precision=1, separator=', ')\n",
        "    print(f'{e.description:<25} {sig_str:>25} {e.lambda_learning_rate:7.2f}')",
    ]),
    md([
        "## 3. Baseline Evolution\n",
        "\n",
        "We apply each event sequentially using the core equation:\n",
        "\n",
        "$$B(t+1) = B(t)(1 - \\lambda) + I(t) \\cdot \\lambda$$\n",
        "\n",
        "Watch how the baseline drifts \u2014 some events barely move it (low $\\lambda$),\n",
        "while others permanently reshape the agent's resting state.",
    ]),
    code([
        "B = Baseline(B0.vector.copy())\n",
        "history = [B.vector.copy()]\n",
        "labels = ['Initial']\n",
        "\n",
        "for event in events:\n",
        "    B = update_baseline(B, event)\n",
        "    history.append(B.vector.copy())\n",
        "    labels.append(event.description)\n",
        "\n",
        "history = np.array(history)\n",
        "\n",
        "hdr = ('Step', 'Event', 'Valence', 'Activation', 'Dominance')\n",
        "print(f'{hdr[0]:<3} {hdr[1]:<25} {hdr[2]:>8} {hdr[3]:>11} {hdr[4]:>10}')\n",
        "print('-' * 60)\n",
        "for i, (lbl, row) in enumerate(zip(labels, history)):\n",
        "    print(f'{i:<3} {lbl:<25} {row[0]:+8.4f} {row[1]:+11.4f} {row[2]:+10.4f}')",
    ]),
    code([
        "fig, ax = plt.subplots(figsize=(12, 6))\n",
        "x = range(len(history))\n",
        "ax.plot(x, history[:, 0], 'o-', label='Valence', color='#3b82f6', linewidth=2.5)\n",
        "ax.plot(x, history[:, 1], 's-', label='Activation', color='#ef4444', linewidth=2.5)\n",
        "ax.plot(x, history[:, 2], '^-', label='Dominance', color='#10b981', linewidth=2.5)\n",
        "\n",
        "ax.set_xticks(x)\n",
        "ax.set_xticklabels(labels, rotation=35, ha='right', fontsize=9)\n",
        "ax.set_ylabel('State Value', fontsize=12)\n",
        "ax.set_title('Baseline Trajectory Through Life Events', fontsize=14)\n",
        "ax.legend(fontsize=11)\n",
        "ax.grid(True, alpha=0.3)\n",
        "ax.axhline(y=0, color='#475569', linestyle='--', alpha=0.5)\n",
        "\n",
        "ax.set_facecolor('#0f172a')\n",
        "fig.patch.set_facecolor('#0f172a')\n",
        "ax.tick_params(colors='#94a3b8')\n",
        "ax.xaxis.label.set_color('#94a3b8')\n",
        "ax.yaxis.label.set_color('#94a3b8')\n",
        "ax.title.set_color('#e2e8f0')\n",
        "for spine in ax.spines.values():\n",
        "    spine.set_color('#334155')\n",
        "plt.tight_layout()\n",
        "plt.show()",
    ]),
    md([
        "## 4. Plasticity Parameter Sweep\n",
        "\n",
        "What happens when the *same event* hits at different plasticity levels?\n",
        "\n",
        "Low $\\lambda$ \u2192 the event barely registers (emotional callus, dissociation).  \n",
        "High $\\lambda$ \u2192 the event rewrites you completely (no buffer, no resistance).",
    ]),
    code([
        "test_signal = np.array([-0.8, 0.5, -0.6])  # Sudden loss\n",
        "lambdas = [0.01, 0.1, 0.3, 0.5, 0.8, 0.95]\n",
        "\n",
        "fig, axes = plt.subplots(2, 3, figsize=(14, 8), sharey=True)\n",
        "dim_labels = ['Valence', 'Activation', 'Dominance']\n",
        "dim_colors = ['#3b82f6', '#ef4444', '#10b981']\n",
        "\n",
        "for idx, lam in enumerate(lambdas):\n",
        "    ax = axes[idx // 3][idx % 3]\n",
        "    B_sweep = Baseline(B0.vector.copy())\n",
        "    sweep_hist = [B_sweep.vector.copy()]\n",
        "    for _ in range(5):\n",
        "        trauma = TraumaForm(test_signal, lam, 'Same event')\n",
        "        B_sweep = update_baseline(B_sweep, trauma)\n",
        "        sweep_hist.append(B_sweep.vector.copy())\n",
        "    sweep_hist = np.array(sweep_hist)\n",
        "    for d in range(3):\n",
        "        ax.plot(sweep_hist[:, d], 'o-', color=dim_colors[d],\n",
        "                label=dim_labels[d] if idx == 0 else None, linewidth=2)\n",
        "    ax.set_title(f'$\\\\lambda$ = {lam}', fontsize=12, color='#e2e8f0')\n",
        "    ax.set_ylim(-1.1, 1.1)\n",
        "    ax.grid(True, alpha=0.3)\n",
        "    ax.set_facecolor('#0f172a')\n",
        "    ax.tick_params(colors='#94a3b8')\n",
        "    for spine in ax.spines.values():\n",
        "        spine.set_color('#334155')\n",
        "\n",
        "axes[0][0].legend(fontsize=9)\n",
        "fig.suptitle('Same Event, Different Plasticity', fontsize=14, color='#e2e8f0')\n",
        "fig.patch.set_facecolor('#0f172a')\n",
        "plt.tight_layout()\n",
        "plt.show()",
    ]),
    md([
        "## 5. Coupling Dynamics ($\\kappa$)\n",
        "\n",
        "Relationships between agents evolve through a coupling coefficient $\\kappa$:\n",
        "\n",
        "$$\\frac{d\\kappa}{dt} = \\alpha(1 - N) - \\beta\\kappa$$\n",
        "\n",
        "where:\n",
        "- $\\alpha$ controls how quickly coupling **grows** in low-novelty (familiar) situations\n",
        "- $\\beta$ controls natural coupling **decay**\n",
        "- $N$ is the **novelty** of an interaction (high novelty = less coupling gain)\n",
        "\n",
        "Below we trace a 10-interaction relationship arc \u2014 from strangers to bonded pair.",
    ]),
    code([
        "interactions = [\n",
        "    Interaction(0.9, 1.0, 'First meeting'),\n",
        "    Interaction(0.7, 1.0, 'Second encounter'),\n",
        "    Interaction(0.5, 2.0, 'Shared project'),\n",
        "    Interaction(0.3, 1.5, 'Growing comfort'),\n",
        "    Interaction(0.2, 2.0, 'Deep conversation'),\n",
        "    Interaction(0.1, 3.0, 'Routine together'),\n",
        "    Interaction(0.8, 1.0, 'Conflict / surprise'),\n",
        "    Interaction(0.4, 2.0, 'Reconciliation'),\n",
        "    Interaction(0.1, 4.0, 'Quiet coexistence'),\n",
        "    Interaction(0.05, 5.0, 'Long-term bond'),\n",
        "]\n",
        "\n",
        "alpha = 0.2\n",
        "beta = 0.05\n",
        "kappa = 0.1\n",
        "kappa_history = [kappa]\n",
        "int_labels = ['Start']\n",
        "\n",
        "for inter in interactions:\n",
        "    kappa = update_kappa(kappa, inter, alpha, beta)\n",
        "    kappa_history.append(kappa)\n",
        "    int_labels.append(inter.description)\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(12, 5))\n",
        "x = range(len(kappa_history))\n",
        "ax.plot(x, kappa_history, 'o-', color='#f59e0b', linewidth=2.5, markersize=8)\n",
        "ax.fill_between(x, kappa_history, alpha=0.2, color='#f59e0b')\n",
        "ax.set_xticks(x)\n",
        "ax.set_xticklabels(int_labels, rotation=35, ha='right', fontsize=9)\n",
        "ax.set_ylabel('Coupling Strength ($\\\\kappa$)', fontsize=12)\n",
        "ax.set_title('Relationship Arc: Coupling Over Time', fontsize=14)\n",
        "ax.grid(True, alpha=0.3)\n",
        "\n",
        "ax.set_facecolor('#0f172a')\n",
        "fig.patch.set_facecolor('#0f172a')\n",
        "ax.tick_params(colors='#94a3b8')\n",
        "ax.xaxis.label.set_color('#94a3b8')\n",
        "ax.yaxis.label.set_color('#94a3b8')\n",
        "ax.title.set_color('#e2e8f0')\n",
        "for spine in ax.spines.values():\n",
        "    spine.set_color('#334155')\n",
        "plt.tight_layout()\n",
        "plt.show()",
    ]),
    md([
        "## 6. State-Space Trajectory\n",
        "\n",
        "The baseline moves through 3D state space. Below are three 2D projection\n",
        "planes, showing how the agent's resting personality drifts through\n",
        "the life events defined above.",
    ]),
    code([
        "pairs = [(0, 1, 'Valence', 'Activation'),\n",
        "         (0, 2, 'Valence', 'Dominance'),\n",
        "         (1, 2, 'Activation', 'Dominance')]\n",
        "\n",
        "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n",
        "for ax, (xi, yi, xl, yl) in zip(axes, pairs):\n",
        "    ax.plot(history[:, xi], history[:, yi], 'o-', color='#8b5cf6',\n",
        "            linewidth=2, markersize=8)\n",
        "    ax.plot(history[0, xi], history[0, yi], 's', color='#10b981',\n",
        "            markersize=12, label='Start', zorder=5)\n",
        "    ax.plot(history[-1, xi], history[-1, yi], 'D', color='#ef4444',\n",
        "            markersize=12, label='End', zorder=5)\n",
        "    for i, lbl in enumerate(labels):\n",
        "        ax.annotate(str(i), (history[i, xi], history[i, yi]),\n",
        "                    fontsize=8, ha='center', va='bottom', color='#94a3b8')\n",
        "    ax.set_xlabel(xl, fontsize=11)\n",
        "    ax.set_ylabel(yl, fontsize=11)\n",
        "    ax.legend(fontsize=9)\n",
        "    ax.grid(True, alpha=0.3)\n",
        "    ax.set_facecolor('#0f172a')\n",
        "    ax.tick_params(colors='#94a3b8')\n",
        "    ax.xaxis.label.set_color('#94a3b8')\n",
        "    ax.yaxis.label.set_color('#94a3b8')\n",
        "    for spine in ax.spines.values():\n",
        "        spine.set_color('#334155')\n",
        "\n",
        "fig.suptitle('Baseline Trajectory \u2014 Three Projection Planes', fontsize=14, color='#e2e8f0')\n",
        "fig.patch.set_facecolor('#0f172a')\n",
        "plt.tight_layout()\n",
        "plt.show()",
    ]),
    md([
        "## Key Takeaways\n",
        "\n",
        "1. **Memory is not storage \u2014 it is drift.** The baseline equation shows that\n",
        "   every experience permanently alters the agent's resting state, weighted by\n",
        "   the plasticity parameter $\\lambda$.\n",
        "\n",
        "2. **Plasticity is the vulnerability dial.** Low $\\lambda$ = resilient but rigid.\n",
        "   High $\\lambda$ = adaptive but fragile. There is no \"correct\" setting \u2014 only\n",
        "   trade-offs.\n",
        "\n",
        "3. **Coupling grows in familiarity, fractures in novelty.** The $\\kappa$ equation\n",
        "   captures how relationships strengthen through routine and weaken through\n",
        "   disruption \u2014 but conflict followed by reconciliation can ultimately strengthen\n",
        "   the bond.\n",
        "\n",
        "4. **State-space trajectories are fingerprints.** Two agents who experience the\n",
        "   same events at different plasticity levels will trace completely different\n",
        "   paths through personality space.\n",
        "\n",
        "---\n",
        "\n",
        "*Everett, B. (2024). Memory as Baseline Deviation (MBD): A Formal Framework\n",
        "for Encoding Persistent Trauma in Autonomous Agents. Zenodo.*  \n",
        "[10.5281/zenodo.17381536](https://doi.org/10.5281/zenodo.17381536)",
    ]),
]

# ═══════════════════════════════════════════════════════════════════════
# NOTEBOOK 04 — Paper 4: Executive Load
# ═══════════════════════════════════════════════════════════════════════

nb04 = {"cells": [], "metadata": META, "nbformat": 4, "nbformat_minor": 4}

nb04["cells"] = [
    md([
        "# Paper 4: The Coupling Asymmetry \u2014 Executive Load as Eigenstate\n",
        "\n",
        "**DOI:** [10.5281/zenodo.18519187](https://doi.org/10.5281/zenodo.18519187)\n",
        "\n",
        "This notebook demonstrates the **Coupling Asymmetry**: the observation that\n",
        "executive dysfunction is not a deficit but an **eigenstate** of the memory\u2013baseline\n",
        "system under excessive coupling load.\n",
        "\n",
        "## The Core Insight\n",
        "\n",
        "Every active coupling $\\kappa_i$ between an agent and a task, person, or obligation\n",
        "consumes a portion of the agent's **executive bandwidth**. The total load is:\n",
        "\n",
        "$$L(t) = \\sum_i \\kappa_i(t) \\cdot w_i$$\n",
        "\n",
        "where $w_i$ is the cognitive weight of coupling $i$ (complexity, emotional cost,\n",
        "time pressure). When $L$ exceeds a critical threshold $L_c$, the system transitions\n",
        "from a **fluid** state (tasks flow, decisions happen) to a **frozen** state\n",
        "(paralysis, avoidance, executive dysfunction).\n",
        "\n",
        "This is not personal failure. It is a **phase transition** \u2014 as physical as\n",
        "water freezing at 0\u00b0C.",
    ]),
    code([
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from matplotlib.patches import FancyBboxPatch\n",
        "import matplotlib.colors as mcolors\n",
        "\n",
        "np.random.seed(42)\n",
        "print('Executive Load diagnostic ready.')",
    ]),
    md([
        "## 1. Defining Coupling Load\n",
        "\n",
        "Each active commitment is a coupling with three parameters:\n",
        "- **$\\kappa$**: bond strength (how tightly coupled you are to this task/person)\n",
        "- **$w$**: cognitive weight (complexity \u00d7 emotional cost \u00d7 urgency)\n",
        "- **$\\kappa \\cdot w$**: the actual load contribution\n",
        "\n",
        "Let's define a realistic weekday for someone with ADHD, clinical anxiety,\n",
        "or burnout \u2014 not extraordinary tasks, just an ordinary Tuesday.",
    ]),
    code([
        "# Define a realistic coupling portfolio\n",
        "couplings = [\n",
        "    # (name, kappa, weight, category)\n",
        "    ('Morning routine',       0.3, 0.2, 'self'),\n",
        "    ('Commute / transit',     0.2, 0.3, 'environment'),\n",
        "    ('Primary work task',     0.8, 0.7, 'work'),\n",
        "    ('Email backlog',         0.5, 0.5, 'work'),\n",
        "    ('Slack messages',        0.4, 0.4, 'work'),\n",
        "    ('Meeting (1pm)',         0.6, 0.6, 'work'),\n",
        "    ('Grocery list',          0.3, 0.3, 'home'),\n",
        "    ('Overdue bill',          0.7, 0.8, 'home'),\n",
        "    ('Text back friend',     0.4, 0.2, 'social'),\n",
        "    ('Partner check-in',     0.6, 0.3, 'social'),\n",
        "    ('Background worry',     0.5, 0.6, 'internal'),\n",
        "    ('Physical discomfort',  0.3, 0.4, 'internal'),\n",
        "]\n",
        "\n",
        "names    = [c[0] for c in couplings]\n",
        "kappas   = np.array([c[1] for c in couplings])\n",
        "weights  = np.array([c[2] for c in couplings])\n",
        "cats     = [c[3] for c in couplings]\n",
        "loads    = kappas * weights\n",
        "\n",
        "total_load = loads.sum()\n",
        "\n",
        "hdr = ('Coupling', '\u03ba', 'w', '\u03ba\u00b7w')\n",
        "print(f'{hdr[0]:<25} {hdr[1]:>5} {hdr[2]:>5} {hdr[3]:>6}')\n",
        "print('-' * 45)\n",
        "for name, k, w, l in zip(names, kappas, weights, loads):\n",
        "    print(f'{name:<25} {k:5.2f} {w:5.2f} {l:6.3f}')\n",
        "print('-' * 45)\n",
        "lbl = 'TOTAL LOAD'\n",
        "pad = ''\n",
        "print(f'{lbl:>25} {pad:>5} {pad:>5} {total_load:6.3f}')",
    ]),
    md([
        "## 2. The Phase Transition Boundary\n",
        "\n",
        "The critical threshold $L_c$ varies by individual (executive capacity,\n",
        "sleep quality, baseline stress). We model it as:\n",
        "\n",
        "$$L_c = L_0 \\cdot (1 - \\text{fatigue}) \\cdot (1 + \\text{rest\\_bonus})$$\n",
        "\n",
        "where $L_0$ is the nominal capacity. When $L > L_c$:\n",
        "\n",
        "$$\\text{executive\\_efficiency}(L) = \\begin{cases}\n",
        "1 & \\text{if } L \\leq L_c \\\\\\\\\n",
        "e^{-\\gamma(L - L_c)} & \\text{if } L > L_c\n",
        "\\end{cases}$$\n",
        "\n",
        "The decay parameter $\\gamma$ controls how steep the cliff is.\n",
        "High $\\gamma$ = sudden collapse (ADHD-pattern). Low $\\gamma$ = gradual degradation (burnout-pattern).",
    ]),
    code([
        "def executive_efficiency(L, L_c, gamma=5.0):\n",
        "    \"\"\"Efficiency as a function of load relative to critical threshold.\"\"\"\n",
        "    if L <= L_c:\n",
        "        return 1.0\n",
        "    return np.exp(-gamma * (L - L_c))\n",
        "\n",
        "def critical_threshold(L0=3.0, fatigue=0.0, rest_bonus=0.0):\n",
        "    \"\"\"Compute L_c from base capacity and modifiers.\"\"\"\n",
        "    return L0 * (1.0 - fatigue) * (1.0 + rest_bonus)\n",
        "\n",
        "# Three scenarios\n",
        "scenarios = [\n",
        "    ('Well-rested',     0.0, 0.2),\n",
        "    ('Normal day',      0.2, 0.0),\n",
        "    ('Sleep-deprived',  0.5, 0.0),\n",
        "]\n",
        "\n",
        "L_range = np.linspace(0, 5, 200)\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(10, 6))\n",
        "colors_scen = ['#10b981', '#f59e0b', '#ef4444']\n",
        "\n",
        "for (label, fatigue, rest), color in zip(scenarios, colors_scen):\n",
        "    Lc = critical_threshold(fatigue=fatigue, rest_bonus=rest)\n",
        "    eff = [executive_efficiency(L, Lc, gamma=4.0) for L in L_range]\n",
        "    ax.plot(L_range, eff, label=f'{label} (Lc={Lc:.2f})', color=color, linewidth=2.5)\n",
        "    ax.axvline(x=Lc, color=color, linestyle=':', alpha=0.5)\n",
        "\n",
        "ax.axvline(x=total_load, color='white', linestyle='--', alpha=0.8, linewidth=1.5)\n",
        "ax.annotate(f'Current load\\n({total_load:.2f})',\n",
        "            xy=(total_load, 0.5), fontsize=10, color='white',\n",
        "            ha='left', va='center',\n",
        "            arrowprops=dict(arrowstyle='->', color='white'))\n",
        "\n",
        "ax.set_xlabel('Total Coupling Load L(t)', fontsize=12)\n",
        "ax.set_ylabel('Executive Efficiency', fontsize=12)\n",
        "ax.set_title('Phase Transition: Fluid \\u2192 Frozen Executive State', fontsize=14)\n",
        "ax.legend(fontsize=10)\n",
        "ax.set_ylim(-0.05, 1.1)\n",
        "ax.grid(True, alpha=0.3)\n",
        "ax.set_facecolor('#0f172a')\n",
        "fig.patch.set_facecolor('#0f172a')\n",
        "ax.tick_params(colors='#94a3b8')\n",
        "ax.xaxis.label.set_color('#94a3b8')\n",
        "ax.yaxis.label.set_color('#94a3b8')\n",
        "ax.title.set_color('#e2e8f0')\n",
        "for spine in ax.spines.values():\n",
        "    spine.set_color('#334155')\n",
        "plt.tight_layout()\n",
        "plt.show()",
    ]),
    md([
        "## 3. The Load Heatmap: Where Is the Weight?\n",
        "\n",
        "Not all couplings are equal. A visual breakdown shows which\n",
        "commitments are actually consuming your bandwidth.",
    ]),
    code([
        "# Sort by load contribution\n",
        "order = np.argsort(loads)[::-1]\n",
        "sorted_names = [names[i] for i in order]\n",
        "sorted_loads = loads[order]\n",
        "sorted_cats  = [cats[i] for i in order]\n",
        "\n",
        "cat_colors = {\n",
        "    'work': '#3b82f6', 'home': '#f59e0b', 'social': '#8b5cf6',\n",
        "    'self': '#10b981', 'environment': '#64748b', 'internal': '#ef4444',\n",
        "}\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(10, 6))\n",
        "bar_colors = [cat_colors[c] for c in sorted_cats]\n",
        "bars = ax.barh(range(len(sorted_names)), sorted_loads, color=bar_colors, edgecolor='#1e293b')\n",
        "ax.set_yticks(range(len(sorted_names)))\n",
        "ax.set_yticklabels(sorted_names, fontsize=10)\n",
        "ax.set_xlabel('Load Contribution (\\u03ba\\u00b7w)', fontsize=12)\n",
        "ax.set_title('Coupling Load Breakdown \\u2014 An Ordinary Tuesday', fontsize=14)\n",
        "ax.invert_yaxis()\n",
        "\n",
        "cumulative = np.cumsum(sorted_loads)\n",
        "ax2 = ax.twiny()\n",
        "ax2.plot(cumulative, range(len(sorted_names)), 'o--', color='white', alpha=0.6, markersize=4)\n",
        "ax2.set_xlabel('Cumulative Load', fontsize=10, color='#94a3b8')\n",
        "\n",
        "for cat, col in cat_colors.items():\n",
        "    ax.barh([], [], color=col, label=cat)\n",
        "ax.legend(loc='lower right', fontsize=9)\n",
        "\n",
        "ax.set_facecolor('#0f172a')\n",
        "fig.patch.set_facecolor('#0f172a')\n",
        "ax.tick_params(colors='#94a3b8')\n",
        "ax2.tick_params(colors='#64748b')\n",
        "ax.xaxis.label.set_color('#94a3b8')\n",
        "ax.title.set_color('#e2e8f0')\n",
        "for spine in ax.spines.values():\n",
        "    spine.set_color('#334155')\n",
        "for spine in ax2.spines.values():\n",
        "    spine.set_color('#334155')\n",
        "plt.tight_layout()\n",
        "plt.show()",
    ]),
    md([
        "## 4. Temporal Dynamics: Load Accumulation Over a Day\n",
        "\n",
        "Load is not static. Couplings activate and deactivate throughout\n",
        "the day. We can model a 16-hour waking period and watch the load\n",
        "curve rise, cross thresholds, and (sometimes) recover.",
    ]),
    code([
        "hours = np.arange(0, 16)\n",
        "hour_labels = [f'{(h+7) % 24}:00' for h in hours]\n",
        "\n",
        "schedules = [\n",
        "    ('Morning routine',     0.3, 0.2,  0,  2),\n",
        "    ('Commute',             0.2, 0.3,  1,  2),\n",
        "    ('Primary work',        0.8, 0.7,  2, 10),\n",
        "    ('Email',               0.5, 0.5,  2, 10),\n",
        "    ('Slack',               0.4, 0.4,  2, 10),\n",
        "    ('Meeting',             0.6, 0.6,  6,  7),\n",
        "    ('Lunch break',        -0.3, 0.5,  5,  6),\n",
        "    ('Commute home',        0.2, 0.3, 10, 11),\n",
        "    ('Grocery run',         0.3, 0.3, 11, 12),\n",
        "    ('Overdue bill',        0.7, 0.8,  0, 16),\n",
        "    ('Partner check-in',    0.6, 0.3, 12, 14),\n",
        "    ('Background worry',    0.5, 0.6,  0, 16),\n",
        "    ('Physical discomfort', 0.3, 0.4,  0, 16),\n",
        "    ('Evening wind-down',  -0.2, 0.3, 14, 16),\n",
        "]\n",
        "\n",
        "load_curve = np.zeros(len(hours))\n",
        "for name, k, w, start, end in schedules:\n",
        "    for h in range(start, min(end, 16)):\n",
        "        load_curve[h] += k * w\n",
        "\n",
        "Lc_rested = critical_threshold(fatigue=0.0, rest_bonus=0.1)\n",
        "Lc_tired  = critical_threshold(fatigue=0.3, rest_bonus=0.0)\n",
        "\n",
        "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True,\n",
        "                                gridspec_kw={'height_ratios': [2, 1]})\n",
        "\n",
        "ax1.fill_between(hours, load_curve, alpha=0.3, color='#8b5cf6')\n",
        "ax1.plot(hours, load_curve, 'o-', color='#8b5cf6', linewidth=2.5, markersize=8)\n",
        "ax1.axhline(y=Lc_rested, color='#10b981', linestyle='--', linewidth=1.5,\n",
        "            label=f'Lc (rested) = {Lc_rested:.1f}')\n",
        "ax1.axhline(y=Lc_tired, color='#ef4444', linestyle='--', linewidth=1.5,\n",
        "            label=f'Lc (fatigued) = {Lc_tired:.1f}')\n",
        "ax1.set_ylabel('Total Load L(t)', fontsize=12)\n",
        "ax1.set_title('Executive Load Over a Day', fontsize=14)\n",
        "ax1.legend(fontsize=10)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "eff_rested = [executive_efficiency(L, Lc_rested, gamma=3.0) for L in load_curve]\n",
        "eff_tired  = [executive_efficiency(L, Lc_tired, gamma=3.0) for L in load_curve]\n",
        "ax2.plot(hours, eff_rested, 'o-', color='#10b981', linewidth=2, label='If well-rested')\n",
        "ax2.plot(hours, eff_tired, 'o-', color='#ef4444', linewidth=2, label='If fatigued')\n",
        "ax2.fill_between(hours, eff_tired, alpha=0.15, color='#ef4444')\n",
        "ax2.set_ylabel('Executive Efficiency', fontsize=12)\n",
        "ax2.set_xlabel('Time of Day', fontsize=12)\n",
        "ax2.set_xticks(hours)\n",
        "ax2.set_xticklabels(hour_labels, rotation=45, fontsize=9)\n",
        "ax2.set_ylim(-0.05, 1.1)\n",
        "ax2.legend(fontsize=10)\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "for ax in [ax1, ax2]:\n",
        "    ax.set_facecolor('#0f172a')\n",
        "    ax.tick_params(colors='#94a3b8')\n",
        "    ax.xaxis.label.set_color('#94a3b8')\n",
        "    ax.yaxis.label.set_color('#94a3b8')\n",
        "    for spine in ax.spines.values():\n",
        "        spine.set_color('#334155')\n",
        "ax1.title.set_color('#e2e8f0')\n",
        "fig.patch.set_facecolor('#0f172a')\n",
        "plt.tight_layout()\n",
        "plt.show()",
    ]),
    md([
        "## 5. Intervention Analysis: What Happens If You Drop One Coupling?\n",
        "\n",
        "The diagnostic value: which single coupling, if resolved, would have\n",
        "the largest impact on peak load?\n",
        "\n",
        "This is the **inverse inertia** question \u2014 where is the smallest\n",
        "push that produces the largest state change?",
    ]),
    code([
        "base_peak = load_curve.max()\n",
        "peak_hour = int(load_curve.argmax())\n",
        "\n",
        "print(f'Current peak load: {base_peak:.3f} (at {hour_labels[peak_hour]})')\n",
        "print(f'Critical threshold (fatigued): {Lc_tired:.2f}')\n",
        "print(f'Overshoot: {base_peak - Lc_tired:+.3f}')\n",
        "print()\n",
        "hdr = ('If you resolve...', 'New peak', '\u0394 peak', 'Still over Lc?')\n",
        "print(f'{hdr[0]:<30} {hdr[1]:>9} {hdr[2]:>8} {hdr[3]:>15}')\n",
        "print('-' * 65)\n",
        "\n",
        "interventions = []\n",
        "for name, k, w, start, end in schedules:\n",
        "    if k < 0:\n",
        "        continue\n",
        "    alt_curve = load_curve.copy()\n",
        "    for h in range(start, min(end, 16)):\n",
        "        alt_curve[h] -= k * w\n",
        "    alt_peak = alt_curve.max()\n",
        "    delta = alt_peak - base_peak\n",
        "    over = alt_peak > Lc_tired\n",
        "    interventions.append((name, alt_peak, delta, over))\n",
        "    print(f'{name:<30} {alt_peak:9.3f} {delta:+8.3f} {\"YES\" if over else \"NO\":>15}')\n",
        "\n",
        "best = min(interventions, key=lambda x: x[1])\n",
        "print(f'\\nHighest-impact single intervention: resolve \"{best[0]}\"')\n",
        "print(f'  Reduces peak load by {abs(best[2]):.3f} \\u2192 {best[1]:.3f}')",
    ]),
    md([
        "## 6. Your Own Load Profile\n",
        "\n",
        "Edit the cell below to map your own couplings. Change the names, $\\kappa$ values,\n",
        "weights, and schedules. Then re-run all cells above to see your personal\n",
        "executive load diagnostic.\n",
        "\n",
        "**Guidelines for scoring:**\n",
        "\n",
        "| Parameter | 0.0\u20130.3 (Low) | 0.4\u20130.6 (Medium) | 0.7\u20131.0 (High) |\n",
        "|-----------|----------------|-------------------|-----------------|\n",
        "| **$\\kappa$** (coupling) | Can ignore for hours | Pops into mind regularly | Constantly pulling attention |\n",
        "| **$w$** (weight) | Trivial, automatic | Requires focus and decisions | Complex, emotionally costly |",
    ]),
    code([
        "# ===== YOUR COUPLINGS \u2014 EDIT HERE =====\n",
        "my_couplings = [\n",
        "    # ('Description',         kappa, weight, category),\n",
        "    ('Primary work task',     0.8,   0.7,   'work'),\n",
        "    ('Email / messages',      0.5,   0.5,   'work'),\n",
        "    ('Household chore',       0.3,   0.3,   'home'),\n",
        "    ('Relationship check-in', 0.6,   0.3,   'social'),\n",
        "    ('Health concern',        0.5,   0.6,   'internal'),\n",
        "    # Add your own...\n",
        "]\n",
        "\n",
        "my_loads = [k * w for _, k, w, _ in my_couplings]\n",
        "my_total = sum(my_loads)\n",
        "my_Lc = critical_threshold(fatigue=0.2)\n",
        "\n",
        "print(f'Your total load:      {my_total:.3f}')\n",
        "print(f'Your threshold (Lc):  {my_Lc:.2f}')\n",
        "state = 'FLUID' if my_total <= my_Lc else 'FROZEN'\n",
        "marker = '\\u2705' if state == 'FLUID' else '\\u26a0\\ufe0f'\n",
        "print(f'Status:               {marker} {state}')\n",
        "print(f'Efficiency:           {executive_efficiency(my_total, my_Lc, gamma=4.0):.1%}')",
    ]),
    md([
        "## Key Takeaways\n",
        "\n",
        "1. **Executive dysfunction is a phase transition**, not a character flaw.\n",
        "   When coupling load $L$ exceeds threshold $L_c$, efficiency collapses\n",
        "   exponentially.\n",
        "\n",
        "2. **The threshold is biological and situational.** Sleep, nutrition,\n",
        "   chronic stress, and neurotype all modulate $L_c$. The same task list\n",
        "   that was manageable yesterday can be paralyzing today.\n",
        "\n",
        "3. **Background couplings are the hidden killers.** Persistent worries,\n",
        "   unresolved obligations, and chronic physical discomfort consume\n",
        "   bandwidth even when you're not actively attending to them.\n",
        "\n",
        "4. **The highest-impact intervention is often not the \"hardest\" task** \u2014\n",
        "   it's the one with the highest $\\kappa \\cdot w$ product that occupies\n",
        "   the most hours. Resolving the overdue bill might free more bandwidth\n",
        "   than finishing the work project.\n",
        "\n",
        "5. **This is not a productivity tool.** It is an **empathy tool**.\n",
        "   Understanding the eigenstate means understanding that the frozen\n",
        "   person is not lazy \u2014 they are in a different phase of the same\n",
        "   system you are in when things are flowing.\n",
        "\n",
        "---\n",
        "\n",
        "*Everett, B. (2025). The Coupling Asymmetry: Executive Dysfunction as an\n",
        "Eigenstate of the Memory\u2013Baseline System. Zenodo.*  \n",
        "[10.5281/zenodo.18519187](https://doi.org/10.5281/zenodo.18519187)",
    ]),
]

# ═══════════════════════════════════════════════════════════════════════
# WRITE BOTH
# ═══════════════════════════════════════════════════════════════════════

for name, nb in [("01_baseline_deviation.ipynb", nb01), ("04_executive_load.ipynb", nb04)]:
    path = os.path.join(NB_DIR, name)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    size = os.path.getsize(path)
    cells = len(nb["cells"])
    print(f"  {name}: {cells} cells, {size:,} bytes")

# Final audit for the forbidden word
for name in ["01_baseline_deviation.ipynb", "04_executive_load.ipynb"]:
    path = os.path.join(NB_DIR, name)
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    if "arousal" in content.lower():
        print(f"  WARNING: '{name}' still contains 'arousal'!")
    else:
        print(f"  {name}: CLEAN (no arousal)")

print("\nDone.")
